
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov  2 2025 10:17:27 IST (Nov  2 2025 04:47:27 UTC)

// Verification Directory fv/dadda8x8 

module full_adder(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__2398(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_94(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5107(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_93(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6260(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_92(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__4319(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_91(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__8428(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_90(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5526(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_89(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6783(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_88(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__3680(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_87(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__1617(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_86(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__2802(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_85(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__1705(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_84(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5122(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_83(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__8246(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_82(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__7098(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_81(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6131(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_80(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__1881(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_79(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5115(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_78(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__7482(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_77(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__4733(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_76(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6161(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_75(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__9315(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_74(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__9945(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_73(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__2883(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_72(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__2346(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_71(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__1666(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_70(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__7410(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_69(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6417(.A (a), .B (b), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_68(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5477(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_67(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__2398(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_66(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5107(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_65(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6260(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_64(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__4319(.A (a), .B (b), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_63(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__8428(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_62(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5526(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_61(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6783(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_60(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__3680(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_59(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__1617(.A (a), .B (b), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_58(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__2802(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_57(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__1705(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_56(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5122(.A (cin), .B (b), .CI (a), .CO (carry), .S (sum));
endmodule

module full_adder_55(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__8246(.A (a), .B (b), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_54(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__7098(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_53(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6131(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_52(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__1881(.A (a), .B (b), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_51(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__5115(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_50(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__7482(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_49(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__4733(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module full_adder_48(a, b, cin, sum, carry);
  input a, b, cin;
  output sum, carry;
  wire a, b, cin;
  wire sum, carry;
  ADDFX1 g85__6161(.A (b), .B (a), .CI (cin), .CO (carry), .S (sum));
endmodule

module half_adder(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__9315(.A (a), .B (b), .CO (carry), .S (sum));
endmodule

module half_adder_101(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__9945(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module half_adder_100(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__2883(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module half_adder_99(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__2346(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module half_adder_98(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__1666(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module half_adder_97(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__7410(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module half_adder_96(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__6417(.A (b), .B (a), .CO (carry), .S (sum));
endmodule

module half_adder_95(a, b, sum, carry);
  input a, b;
  output sum, carry;
  wire a, b;
  wire sum, carry;
  ADDHXL g26__5477(.A (a), .B (b), .CO (carry), .S (sum));
endmodule

module dadda8x8(A, B, P);
  input [7:0] A, B;
  output [15:0] P;
  wire [7:0] A, B;
  wire [15:0] P;
  wire [7:0] \pp[0] ;
  wire [7:0] \pp[1] ;
  wire [7:0] \pp[2] ;
  wire [7:0] \pp[3] ;
  wire [7:0] \pp[4] ;
  wire [7:0] \pp[5] ;
  wire [7:0] \pp[6] ;
  wire [7:0] \pp[7] ;
  wire c11, c21, c22, c31, c32, c33, c41, c42;
  wire c43, c44, c51, c52, c53, c54, c55, c61;
  wire c62, c63, c64, c65, c66, c71, c72, c73;
  wire c74, c75, c76, c77, c81, c82, c83, c84;
  wire c85, c86, c87, c91, c92, c93, c94, c95;
  wire c96, c101, c102, c103, c104, c105, c111, c112;
  wire c113, c114, c121, c122, c123, c131, c132, s21;
  wire s31, s32, s41, s42, s43, s51, s52, s53;
  wire s54, s61, s62, s63, s64, s65, s71, s72;
  wire s73, s74, s75, s76, s81, s82, s83, s84;
  wire s85, s86, s91, s92, s93, s94, s95, s101;
  wire s102, s103, s104, s111, s112, s113, s121, s122;
  wire s131;
  full_adder fa21(\pp[0] [2], \pp[1] [1], \pp[2] [0], s21, c21);
  full_adder_94 fa31(\pp[0] [3], \pp[1] [2], \pp[2] [1], s31, c31);
  full_adder_93 fa32(s31, \pp[3] [0], c21, s32, c32);
  full_adder_92 fa41(\pp[0] [4], \pp[1] [3], \pp[2] [2], s41, c41);
  full_adder_91 fa42(s41, \pp[3] [1], \pp[4] [0], s42, c42);
  full_adder_90 fa43(s42, c31, c32, s43, c43);
  full_adder_89 fa51(\pp[0] [5], \pp[1] [4], \pp[2] [3], s51, c51);
  full_adder_88 fa52(s51, \pp[3] [2], \pp[4] [1], s52, c52);
  full_adder_87 fa53(s52, \pp[5] [0], c41, s53, c53);
  full_adder_86 fa54(s53, c42, c43, s54, c54);
  full_adder_85 fa61(\pp[0] [6], \pp[1] [5], \pp[2] [4], s61, c61);
  full_adder_84 fa62(s61, \pp[3] [3], \pp[4] [2], s62, c62);
  full_adder_83 fa63(s62, \pp[5] [1], \pp[6] [0], s63, c63);
  full_adder_82 fa64(s63, c51, c52, s64, c64);
  full_adder_81 fa65(s64, c53, c54, s65, c65);
  full_adder_80 fa71(\pp[0] [7], \pp[1] [6], \pp[2] [5], s71, c71);
  full_adder_79 fa72(s71, \pp[3] [4], \pp[4] [3], s72, c72);
  full_adder_78 fa73(s72, \pp[5] [2], \pp[6] [1], s73, c73);
  full_adder_77 fa74(s73, \pp[7] [0], c61, s74, c74);
  full_adder_76 fa75(s74, c62, c63, s75, c75);
  full_adder_75 fa76(s75, c64, c65, s76, c76);
  full_adder_74 fa81(\pp[1] [7], \pp[2] [6], \pp[3] [5], s81, c81);
  full_adder_73 fa82(s81, \pp[4] [4], \pp[5] [3], s82, c82);
  full_adder_72 fa83(s82, \pp[6] [2], \pp[7] [1], s83, c83);
  full_adder_71 fa84(s83, c71, c72, s84, c84);
  full_adder_70 fa85(s84, c73, c74, s85, c85);
  full_adder_69 fa86(s85, c75, c76, s86, c86);
  full_adder_68 fa91(\pp[2] [7], \pp[3] [6], \pp[4] [5], s91, c91);
  full_adder_67 fa92(s91, \pp[5] [4], \pp[6] [3], s92, c92);
  full_adder_66 fa93(s92, \pp[7] [2], c81, s93, c93);
  full_adder_65 fa94(s93, c82, c83, s94, c94);
  full_adder_64 fa95(s94, c84, c85, s95, c95);
  full_adder_63 fa96(s95, c86, c87, P[9], c96);
  full_adder_62 fa101(\pp[3] [7], \pp[4] [6], \pp[5] [5], s101, c101);
  full_adder_61 fa102(s101, \pp[6] [4], \pp[7] [3], s102, c102);
  full_adder_60 fa103(s102, c91, c92, s103, c103);
  full_adder_59 fa104(s103, c93, c94, s104, c104);
  full_adder_58 fa105(s104, c95, c96, P[10], c105);
  full_adder_57 fa111(\pp[4] [7], \pp[5] [6], \pp[6] [5], s111, c111);
  full_adder_56 fa112(s111, \pp[7] [4], c101, s112, c112);
  full_adder_55 fa113(s112, c102, c103, s113, c113);
  full_adder_54 fa114(s113, c104, c105, P[11], c114);
  full_adder_53 fa121(\pp[5] [7], \pp[6] [6], \pp[7] [5], s121, c121);
  full_adder_52 fa122(s121, c111, c112, s122, c122);
  full_adder_51 fa123(s122, c113, c114, P[12], c123);
  full_adder_50 fa131(\pp[6] [7], \pp[7] [6], c121, s131, c131);
  full_adder_49 fa132(s131, c122, c123, P[13], c132);
  full_adder_48 fa141(\pp[7] [7], c131, c132, P[14], P[15]);
  half_adder ha11(\pp[0] [1], \pp[1] [0], P[1], c11);
  half_adder_101 ha22(s21, c11, P[2], c22);
  half_adder_100 ha33(s32, c22, P[3], c33);
  half_adder_99 ha44(s43, c33, P[4], c44);
  half_adder_98 ha55(s54, c44, P[5], c55);
  half_adder_97 ha66(s65, c55, P[6], c66);
  half_adder_96 ha77(s76, c66, P[7], c77);
  half_adder_95 ha87(s86, c77, P[8], c87);
  AND2X1 g657__2398(.A (B[0]), .B (A[7]), .Y (\pp[0] [7]));
  AND2X1 g658__5107(.A (B[7]), .B (A[6]), .Y (\pp[7] [6]));
  AND2X1 g659__6260(.A (B[7]), .B (A[4]), .Y (\pp[7] [4]));
  AND2X1 g660__4319(.A (B[1]), .B (A[1]), .Y (\pp[1] [1]));
  AND2X1 g661__8428(.A (B[2]), .B (A[2]), .Y (\pp[2] [2]));
  AND2X1 g662__5526(.A (B[3]), .B (A[3]), .Y (\pp[3] [3]));
  AND2X1 g663__6783(.A (B[7]), .B (A[0]), .Y (\pp[7] [0]));
  AND2X1 g664__3680(.A (B[5]), .B (A[5]), .Y (\pp[5] [5]));
  AND2X1 g665__1617(.A (B[5]), .B (A[2]), .Y (\pp[5] [2]));
  AND2X1 g666__2802(.A (B[7]), .B (A[7]), .Y (\pp[7] [7]));
  AND2X1 g667__1705(.A (B[1]), .B (A[2]), .Y (\pp[1] [2]));
  AND2X1 g668__5122(.A (B[0]), .B (A[2]), .Y (\pp[0] [2]));
  AND2X1 g669__8246(.A (B[0]), .B (A[3]), .Y (\pp[0] [3]));
  AND2X1 g670__7098(.A (B[0]), .B (A[4]), .Y (\pp[0] [4]));
  AND2X1 g671__6131(.A (B[1]), .B (A[0]), .Y (\pp[1] [0]));
  AND2X1 g672__1881(.A (B[5]), .B (A[1]), .Y (\pp[5] [1]));
  AND2X1 g673__5115(.A (B[0]), .B (A[0]), .Y (P[0]));
  AND2X1 g674__7482(.A (B[0]), .B (A[6]), .Y (\pp[0] [6]));
  AND2X1 g675__4733(.A (B[5]), .B (A[0]), .Y (\pp[5] [0]));
  AND2X1 g676__6161(.A (B[1]), .B (A[3]), .Y (\pp[1] [3]));
  AND2X1 g677__9315(.A (B[1]), .B (A[4]), .Y (\pp[1] [4]));
  AND2X1 g678__9945(.A (B[1]), .B (A[5]), .Y (\pp[1] [5]));
  AND2X1 g679__2883(.A (B[0]), .B (A[5]), .Y (\pp[0] [5]));
  AND2X1 g680__2346(.A (B[4]), .B (A[7]), .Y (\pp[4] [7]));
  AND2X1 g681__1666(.A (B[6]), .B (A[7]), .Y (\pp[6] [7]));
  AND2X1 g682__7410(.A (B[2]), .B (A[0]), .Y (\pp[2] [0]));
  AND2X1 g683__6417(.A (B[4]), .B (A[6]), .Y (\pp[4] [6]));
  AND2X1 g684__5477(.A (B[2]), .B (A[3]), .Y (\pp[2] [3]));
  AND2X1 g685__2398(.A (B[2]), .B (A[4]), .Y (\pp[2] [4]));
  AND2X1 g686__5107(.A (B[2]), .B (A[5]), .Y (\pp[2] [5]));
  AND2X1 g687__6260(.A (B[0]), .B (A[1]), .Y (\pp[0] [1]));
  AND2X1 g688__4319(.A (B[6]), .B (A[6]), .Y (\pp[6] [6]));
  AND2X1 g689__8428(.A (B[6]), .B (A[3]), .Y (\pp[6] [3]));
  AND2X1 g690__5526(.A (B[3]), .B (A[0]), .Y (\pp[3] [0]));
  AND2X1 g691__6783(.A (B[4]), .B (A[5]), .Y (\pp[4] [5]));
  AND2X1 g692__3680(.A (B[3]), .B (A[2]), .Y (\pp[3] [2]));
  AND2X1 g693__1617(.A (B[3]), .B (A[5]), .Y (\pp[3] [5]));
  AND2X1 g694__2802(.A (B[4]), .B (A[4]), .Y (\pp[4] [4]));
  AND2X1 g695__1705(.A (B[4]), .B (A[3]), .Y (\pp[4] [3]));
  AND2X1 g696__5122(.A (B[3]), .B (A[7]), .Y (\pp[3] [7]));
  AND2X1 g697__8246(.A (B[7]), .B (A[3]), .Y (\pp[7] [3]));
  AND2X1 g698__7098(.A (B[6]), .B (A[5]), .Y (\pp[6] [5]));
  AND2X1 g699__6131(.A (B[4]), .B (A[2]), .Y (\pp[4] [2]));
  AND2X1 g700__1881(.A (B[3]), .B (A[4]), .Y (\pp[3] [4]));
  AND2X1 g701__5115(.A (B[4]), .B (A[1]), .Y (\pp[4] [1]));
  AND2X1 g702__7482(.A (B[4]), .B (A[0]), .Y (\pp[4] [0]));
  AND2X1 g703__4733(.A (B[6]), .B (A[4]), .Y (\pp[6] [4]));
  AND2X1 g704__6161(.A (B[3]), .B (A[6]), .Y (\pp[3] [6]));
  AND2X1 g705__9315(.A (B[2]), .B (A[7]), .Y (\pp[2] [7]));
  AND2X1 g706__9945(.A (B[7]), .B (A[5]), .Y (\pp[7] [5]));
  AND2X1 g707__2883(.A (B[7]), .B (A[2]), .Y (\pp[7] [2]));
  AND2X1 g708__2346(.A (B[5]), .B (A[3]), .Y (\pp[5] [3]));
  AND2X1 g709__1666(.A (B[1]), .B (A[6]), .Y (\pp[1] [6]));
  AND2X1 g710__7410(.A (B[1]), .B (A[7]), .Y (\pp[1] [7]));
  AND2X1 g711__6417(.A (B[2]), .B (A[1]), .Y (\pp[2] [1]));
  AND2X1 g712__5477(.A (B[5]), .B (A[7]), .Y (\pp[5] [7]));
  AND2X1 g713__2398(.A (B[2]), .B (A[6]), .Y (\pp[2] [6]));
  AND2X1 g714__5107(.A (B[6]), .B (A[2]), .Y (\pp[6] [2]));
  AND2X1 g715__6260(.A (B[3]), .B (A[1]), .Y (\pp[3] [1]));
  AND2X1 g716__4319(.A (B[6]), .B (A[1]), .Y (\pp[6] [1]));
  AND2X1 g717__8428(.A (B[6]), .B (A[0]), .Y (\pp[6] [0]));
  AND2X1 g718__5526(.A (B[7]), .B (A[1]), .Y (\pp[7] [1]));
  AND2X1 g719__6783(.A (B[5]), .B (A[6]), .Y (\pp[5] [6]));
  AND2X1 g720__3680(.A (B[5]), .B (A[4]), .Y (\pp[5] [4]));
endmodule

